version: '2'
services:
    recadastro-app:
        image: recadastro
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://recadastro-postgresql:5432/recadastro
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=recadastro-elasticsearch:9300
        ports:
            - 8080:8080
    recadastro-postgresql:
        extends:
            file: postgresql.yml
            service: recadastro-postgresql
    recadastro-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: recadastro-elasticsearch
