version: '2'
services:
    recadastro-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/recadastro/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=recadastro
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
